// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPgzn5DdfoPHkpvIp7a14Gn3nhzwSQioA',
    appId: '1:548600571761:web:49a3db277e31658590f8d0',
    messagingSenderId: '548600571761',
    projectId: 'flutterhabit',
    authDomain: 'flutterhabit.firebaseapp.com',
    storageBucket: 'flutterhabit.appspot.com',
    measurementId: 'G-LXCS4VG3PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOaHjtxUZjqhnAsKfgYg7Eawr4D83jsIo',
    appId: '1:548600571761:android:310401943512051590f8d0',
    messagingSenderId: '548600571761',
    projectId: 'flutterhabit',
    storageBucket: 'flutterhabit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSjcOpG2puMPrAAUVXmQY5YoOZYe477yw',
    appId: '1:548600571761:ios:9eb17d3b63551c6290f8d0',
    messagingSenderId: '548600571761',
    projectId: 'flutterhabit',
    storageBucket: 'flutterhabit.appspot.com',
    iosClientId: '548600571761-sj3iclf03854mskilt49bnl78lr9mna8.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitSpeedCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSjcOpG2puMPrAAUVXmQY5YoOZYe477yw',
    appId: '1:548600571761:ios:9eb17d3b63551c6290f8d0',
    messagingSenderId: '548600571761',
    projectId: 'flutterhabit',
    storageBucket: 'flutterhabit.appspot.com',
    iosClientId: '548600571761-sj3iclf03854mskilt49bnl78lr9mna8.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitSpeedCode',
  );
}
